name: Push to branch

on:
  push:
    branches:
      - develop


jobs:
  push_backend:
    name: Deploy to gh-pages
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v1.4.4
        with:
          node-version: "14"
      - name: Install deps
        run: npm ci
      - name: Deploy new version to master
        run: npm run deploy