name: Push to branch

on:
  push:
    branches:
      - develop


jobs:
  push_backend:
    name: Deploy to gh-pages
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v1.4.4
        with:
          node-version: "14"
      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: master
          folder: build